name: Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Run Bandit & Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit semgrep

      - name: Run Bandit Security Scan
        run: bandit -r . --ini bandit.yaml | tee bandit-report.txt || true

      - name: Run Semgrep Security Scan
        run: semgrep --config=auto --error --json > semgrep-report.json || true

      - name: Analyze Security Reports
        id: analyze_results
        run: |
          CRITICAL_FOUND=$(grep -E 'CRITICAL|HIGH' bandit-report.txt | wc -l)
          if [[ "$CRITICAL_FOUND" -gt 0 ]]; then
            echo "CRITICAL_VULN=true" >> $GITHUB_ENV
          else
            echo "CRITICAL_VULN=false" >> $GITHUB_ENV
          fi

      - name: Block PR if Critical Vulnerability Found
        if: env.CRITICAL_VULN == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Block: Critical vulnerabilities detected in the security scan."
            });
            core.setFailed("Critical vulnerabilities found. Blocking PR.")
